# Generated by Django 6.0.1 on 2026-01-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason_type',
            field=models.CharField(blank=True, choices=[('patient_cancelled', 'Пациент отменил'), ('doctor_cancelled', 'Врач отменил'), ('emergency', 'Экстренная ситуация'), ('other', 'Другое')], help_text='Выберите из списка', max_length=20, null=True, verbose_name='Тип причины отмены'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=15, help_text='Кратно 10 минутам', verbose_name='Длительность приема (мин)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены (комментарий)'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'scheduled')), fields=('doctor', 'date_time'), name='unique_doctor_time'),
        ),
    ]
