# Generated by Django 6.0.1 on 2026-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_document_is_active_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('waiting', 'Ожидает'), ('active', 'На приёме'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('no_show', 'Не пришел')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
    ]
